animations {
    enabled = true
    bezier = hyprglass, 0.16, 1, 0.3, 1
    animation = windows, 1, 4, hyprglass, popin 88%
    animation = windowsOut, 1, 3, hyprglass, popin 88%
    animation = border, 1, 5, hyprglass
    animation = fade, 1, 4, hyprglass
    animation = workspaces, 1, 4, hyprglass, slide
}
