$mod = SUPER
$terminal = kitty
$fileManager = nautilus
$launcher = fuzzel

bind = $mod, RETURN, exec, $terminal
bind = $mod, SPACE, exec, $launcher
bind = $mod, Q, killactive,
bind = $mod, F, fullscreen,
bind = $mod, E, exec, $fileManager
bind = $mod SHIFT, L, exec, hyprlock
bind = $mod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind = $mod, W, exec, kitty --class hyprglass-float --title "Hyprglass :: Wi-Fi" -e hyprglass wifi
bind = $mod, B, exec, kitty --class hyprglass-float --title "Hyprglass :: Bluetooth" -e hyprglass bluetooth
bind = $mod, M, exec, kitty --class hyprglass-float --title "Hyprglass :: LTE" -e hyprglass lte
bind = $mod, A, exec, kitty --class hyprglass-float --title "Hyprglass :: Audio" -e hyprglass audio
bind = $mod, D, exec, kitty --class hyprglass-float --title "Hyprglass :: Display" -e hyprglass display
bind = $mod, slash, exec, kitty --class hyprglass-float --title "Hyprglass :: Shortcuts" -e sh -lc 'less ~/.config/hyprglass/docs/shortcuts.md'

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
