general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    col.active_border = rgba(c084fcee) rgba(60a5faee) 45deg
    col.inactive_border = rgba(1e293b66)
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
}
