general {
    gaps_in = 7
    gaps_out = 14
    border_size = 1
    col.active_border = $hg_accent $hg_accent_2 35deg
    col.inactive_border = $hg_border
    layout = dwindle
}

dwindle {
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
}
