windowrulev2 = float, class:^(hyprglass-float)$
windowrulev2 = size 920 620, class:^(hyprglass-float)$
windowrulev2 = center, class:^(hyprglass-float)$
windowrulev2 = opacity 0.94 0.90, class:^(hyprglass-float)$
windowrulev2 = suppressevent maximize, class:.*
layerrule = blur, waybar
layerrule = ignorezero, waybar
